export const weights = [
  { option: 100, value: 100 },
  { option: 200, value: 200 },
  { option: 300, value: 300 },
  { option: 400, value: 400 },
  { option: 500, value: 500 },
  { option: 600, value: 600 },
  { option: 700, value: 700 },
  { option: 800, value: 800 },
  { option: 900, value: 900 },
  { option: "Bold", value: "bold" },
  { option: "Bolder", value: "bolder" },
  { option: "Inherit", value: "inherit" },
  { option: "Initial", value: "initial" },
  { option: "Lighter", value: "lighter" },
  { option: "Normal", value: "normal" },
  { option: "Revert", value: "revert" },
  { option: "Unset", value: "unset" },
];
